Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "cuDNN"
   Try: "module spider cuDNN" to see how to load the module(s).



{'batch_size': 1024, 'alpha': 1.0, 'epochs': 200, 'patience': 20, 'expert_type': 'predict_biasedK', 'n_classes': 10, 'k': 5, 'n_experts': 2, 'lr': 0.1, 'weight_decay': 0.0005, 'warmup_epochs': 20, 'loss_type': 'ova', 'ckp_dir': './Models', 'experiment_name': 'multiple_experts'}
Training for n=1
Traceback (most recent call last):
  File "main.py", line 348, in <module>
    main(config)
  File "main.py", line 316, in main
    train(model, trainD, valD, expert_fns, config)
  File "main.py", line 262, in train
    iters, train_loss = train_epoch(iters,
  File "main.py", line 204, in train_epoch
    loss = loss_fn(output, target[:, 0], collection_Ms, n_classes)
TypeError: ova() takes 4 positional arguments but 5 were given
srun: error: r34n2: task 0: Exited with exit code 1
