Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "cuDNN"
   Try: "module spider cuDNN" to see how to load the module(s).



cuda:3
cuda:0
{'batch_size': 1024, 'alpha': 1.0, 'epochs': 100, 'patience': 20, 'expert_type': 'predict', 'n_classes': 10, 'k': 5, 'n_experts': 2, 'lr': 0.1, 'weight_decay': 0.0005, 'warmup_epochs': 0, 'loss_type': 'softmax', 'ckp_dir': './softmax_increase_experts/', 'experiment_name': 'multiple_experts'}
n is 1
Evaluate...
Traceback (most recent call last):
  File "analyse_increase_experts.py", line 157, in <module>
    validation(model_name, expert_fns, config)
  File "analyse_increase_experts.py", line 99, in validation
    get('test', test_dl)
  File "analyse_increase_experts.py", line 68, in get
    result_ = evaluate(model, expert_fns, loss_fn, n_classes+len(expert_fns), dl, config)
  File "/home/rverma/Multi-L2D/CIFAR-10/main_increase_experts.py", line 61, in evaluate
    images, labels = images.to(device), labels.to(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
srun: error: r30n4: task 0: Exited with exit code 1
